// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTjLHb5HNP6rqEOm0fzklKnptkVpauUKk',
    appId: '1:757843972506:web:ee6dc81bd222881cc66a23',
    messagingSenderId: '757843972506',
    projectId: 'sarpery-dace7',
    authDomain: 'sarpery-dace7.firebaseapp.com',
    storageBucket: 'sarpery-dace7.appspot.com',
    measurementId: 'G-JCN5ZZ6YM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb5g7EMBofI9LQp4sQ6u8ra_04DFHMk-s',
    appId: '1:757843972506:android:75e16482721a85bec66a23',
    messagingSenderId: '757843972506',
    projectId: 'sarpery-dace7',
    storageBucket: 'sarpery-dace7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcB5MSxoFWF2_5CYD_vESkp554cnw_soo',
    appId: '1:757843972506:ios:8ad3cc75b5755f8ec66a23',
    messagingSenderId: '757843972506',
    projectId: 'sarpery-dace7',
    storageBucket: 'sarpery-dace7.appspot.com',
    iosClientId: '757843972506-0d648b58paaja04f3dsglsrcm4gce29h.apps.googleusercontent.com',
    iosBundleId: 'com.example.updapp',
  );
}
